# Generated by Django 5.2.4 on 2025-07-23 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0002_alter_question_question_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_ru', models.TextField(blank=True, null=True, verbose_name='Ответ (рус)')),
                ('answer_kz', models.TextField(blank=True, null=True, verbose_name='Жауап (қаз)')),
                ('answer_image_ru', models.ImageField(blank=True, null=True, upload_to='images/answers/ru/', verbose_name='Изображение (рус)')),
                ('answer_image_kz', models.ImageField(blank=True, null=True, upload_to='images/answers/kz/', verbose_name='Сурет (қаз)')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='question.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['id'],
            },
        ),
    ]
