# Generated by Django 5.2.4 on 2025-08-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='answer',
            name='is_correct_kz',
            field=models.BooleanField(default=False, verbose_name='Дұрыс жауап (қаз)'),
        ),
        migrations.AddField(
            model_name='answer',
            name='is_correct_ru',
            field=models.BooleanField(default=False, verbose_name='Правильный ответ (рус)'),
        ),
    ]
