# Generated by Django 5.2.4 on 2025-07-23 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0003_alter_subjects_options_alter_subjects_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ru', models.TextField(verbose_name='Вопрос (рус)')),
                ('question_kz', models.TextField(blank=True, null=True, verbose_name='Сұрақ (қаз)')),
                ('question_image_ru', models.ImageField(blank=True, null=True, upload_to='images/questions/ru/', verbose_name='Изображение (рус)')),
                ('question_image_kz', models.ImageField(blank=True, null=True, upload_to='images/questions/kz/', verbose_name='Сурет (қаз)')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='subjects.subjects', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['id'],
            },
        ),
    ]
