# Generated by Django 5.2.4 on 2025-07-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Вопрос (рус)'),
        ),
    ]
