# Generated by Django 5.2.4 on 2025-07-30 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0004_delete_diagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('cutoff', models.IntegerField(blank=True, null=True, verbose_name='Минимум для поступления')),
                ('subject_set', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='exam.subjectset', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
            },
        ),
    ]
