# Generated by Django 5.2.4 on 2025-07-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0003_alter_subjects_options_alter_subjects_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Subject Set Name')),
                ('subjects', models.ManyToManyField(related_name='subject_sets', to='subjects.subjects', verbose_name='Subjects')),
            ],
            options={
                'verbose_name': 'Subject Set',
                'verbose_name_plural': 'Subject Sets',
            },
        ),
    ]
