# Generated by Django 5.2.4 on 2025-07-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parents_names', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО родителя')),
                ('student_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя студента')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона')),
                ('school_class', models.CharField(blank=True, max_length=255, null=True, verbose_name='Класс')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Регион')),
                ('language', models.CharField(blank=True, max_length=255, null=True, verbose_name='Язык')),
                ('points', models.IntegerField(blank=True, null=True, verbose_name='Баллы')),
            ],
        ),
        migrations.AlterModelOptions(
            name='subjectset',
            options={'verbose_name': 'Сборник Предметов', 'verbose_name_plural': 'Сборники Предметов'},
        ),
    ]
