# Generated by Django 5.2.4 on 2025-07-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_student_alter_subjectset_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=255, verbose_name='ФИО родителя')),
                ('student_name', models.CharField(max_length=255, verbose_name='Имя ученика')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('school_class', models.CharField(max_length=10, verbose_name='Класс')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('language', models.CharField(max_length=50, verbose_name='Язык обучения')),
                ('history_score', models.PositiveIntegerField(verbose_name='История Казахстана')),
                ('math_literacy_score', models.PositiveIntegerField(verbose_name='Математическая грамотность')),
                ('reading_literacy_score', models.PositiveIntegerField(verbose_name='Грамотность чтения')),
                ('profile_subject_1_name', models.CharField(max_length=100, verbose_name='Профильный предмет №1')),
                ('profile_subject_1_score', models.PositiveIntegerField(verbose_name='Баллы по профильному предмету №1')),
                ('profile_subject_2_name', models.CharField(max_length=100, verbose_name='Профильный предмет №2')),
                ('profile_subject_2_score', models.PositiveIntegerField(verbose_name='Баллы по профильному предмету №2')),
                ('total_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Суммарные баллы')),
                ('correct_percentage', models.FloatField(blank=True, null=True, verbose_name='Процент правильных ответов')),
                ('admission_probability', models.FloatField(blank=True, null=True, verbose_name='Вероятность поступления (%)')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Рекомендации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Диагностика',
                'verbose_name_plural': 'Диагностики',
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
