# Generated by Django 5.2.4 on 2025-07-29 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_diagnosis_delete_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diagnosis',
        ),
    ]
