# Generated by Django 5.2.4 on 2025-07-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название категории')),
                ('type', models.CharField(choices=[('Exact', 'Точная наука'), ('Natural', 'Естественная наука')], max_length=10, verbose_name='Тип')),
                ('subject_type', models.CharField(choices=[('Основной', 'Основной предмет'), ('Профильный', 'Профильный предмет')], max_length=20, verbose_name='Тип предмета')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
    ]
