# Generated by Django 5.2.4 on 2025-07-23 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Subjects',
        ),
    ]
