# Generated by Django 5.2.4 on 2025-07-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_rename_category_subjects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjects',
            options={'ordering': ['title'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterField(
            model_name='subjects',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название предмета'),
        ),
    ]
